services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: ./Backend.API/Dockerfile
    restart: always
    environment:
      DatabaseConnectionString: Host=localhost;Port=5432;Username=appuser;Password=secret;Database=appdb;Include Error Detail=true;
    ports:
      - '5000:5000'
    depends_on:
      - db
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
volumes:
  db-data:
